### ISSUE TITLE
simple-file-cards-and-form

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#1]
## Value Proposition

**As a** User
**I need** to create file cards 
**to be able to** memorize information faster and recap lessons everywhere with my smartphone

## Description

<img src="https://user-images.githubusercontent.com/98178752/159695376-ff655eeb-3ebf-455d-af83-11fbce4d920f.png" alt="Wireframe CardList, CardForm and empty state" width="500">

## Acceptance Criteria

- [x] empty state: form with required inputs, without 'zur Liste'-button; title: 'Erstelle deine **erste** Karte!'
- [x] change sites with conditional rendering
- [x] empty inputs or only whitespace does not submit
- [x] text has a max length of 200 characters
- [x] new cards show up on first position
- [x] text wraps in cards (no ellipses)
- [ ] <del>click on 'zur Liste' shows alert if input is filled out and not submitted, yet</del>     
        **new issue:** #11

## Tasks

- [x] create branch `simple-file-cards-and-form`
- [x] create CardForm.spec
- [x] create CardForm component
- [x] create CardForm.stories
- [x] create Card.spec
- [x] create Card component
- [x] create Card.stories
- [x] add list of Cards and CardForm to App (conditional rendering)
- [x] update styles
- [x] test on different devices/browsers
