### ISSUE TITLE
right-wrong-counter

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#10]
## Value Proposition

**As a** User
**I need** to mark if my answer was right or wrong
**to be able to** decide which ones I want to repeat more often (and eventually want to bookmark)

## Description
<img src="https://user-images.githubusercontent.com/98178752/160128043-fb55850b-7be8-4e8d-af6f-4542fd775303.png" alt="wireframe: card with right wrong counter" width="300"/>

Branch: `right-wrong-counter`

## Acceptance Criteria

- [x] click on button 'richtig' increases counter 'richtig'
- [x] click on button 'falsch' increases counter 'falsch'
- [x] counter is saved in local storage

## Tasks

- [x] update Card.spec
- [x] update Card.stories
- [x] update Card
- [x] add counter logic
- [x] update App
- [x] update localStorage()
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
