### ISSUE TITLE
alert-when-change-page-without-submit

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#11]

**Comment by Ju-Schn** [comment]
## Value Proposition

**As a** User
**I need** to be reminded when my input is not submitted and I want to change pages
**to be able to** not lose any information

## Description

alert shows up on click of button 'zur Liste' when inputs are filled out, but not submitted



## Acceptance Criteria

- [ ] click on 'zur Liste' shows alert if input is filled out and not submitted, yet

## Tasks

- [ ] add alert
- [ ] update CardForm
- [ ] update CardForm.spec
- [ ] update styling
- [ ] test on different devices/browsers
