### ISSUE TITLE
create-card-form

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#2]
## Value Proposition

**As a** User
**I need** a form
**to be able to** create my own file cards

## Description

![create-card-form(1)](https://user-images.githubusercontent.com/98178752/159541152-b8439b34-6b2b-4407-b897-f79d9683b3a0.png)

## Acceptance Criteria

- [ ] empty inputs or only whitespace does not submit
- [ ] text has a max length of 200 characters
- [ ] new cards show up on first position
- [ ] text wraps in cards (no ellipses)

## Tasks

- [ ] create branch `create-card-form`
- [ ] create CardForm with storybook and specs
- [ ] add CardForm to App
- [ ] add button 'Create' to CardList
- [ ] update styles
- [ ] test on different devices/browsers

**Comment by Ju-Schn** [comment]
merged with first issue: [https://github.com/Ju-Schn/capstone-project/issues/1](url)
