### ISSUE TITLE
flip-cards

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#22]
## Value Proposition

**As a** User
**I need** to flip cards and the answer is on the back
**to be able to** have more fun studying and to have a more authentic card-learning experience

## Description
<img src="https://user-images.githubusercontent.com/98178752/162563757-530e9f00-7d12-4ac6-b0a2-e31fdfc9e671.png" alt="wireframe: flip effect card" width="
300"/>

Branch: `flip-cards`

## Acceptance Criteria

- [ ] click on 'drehen' button shows answer on the back of the card
- [ ] pin sign is on the back of the card
- [ ] right wrong counter is on the back of the card

## Tasks

- [ ] update Card
- [ ] update Card.spec
- [ ] update Card.stories
- [ ] add flip animation
- [ ] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
