### ISSUE TITLE
difficulty-filter

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#23]
## Value Proposition

**As a** User
**I need** to decide if I want to practice more difficult or easier cards
**to be able to** stay motivated and practice the cards I don't know that well right before tests

## Description
<img src="https://user-images.githubusercontent.com/98178752/162564544-667e2bc4-3292-4572-b3a3-bcbd2d7c24df.png" alt="wireframe: card with difficulty filter" width="300"/>

Branch: `difficulty-filter`

## Acceptance Criteria

- [x] filter with categories: 'einfach', 'mittel', 'schwer'
- [x] difficulty depends on quotient of right-wrong-counter
- [x] difficulty is NOT shown on the card, to prevent lack of motivation

## Tasks

- [x] update Home (page)
- [x] add difficulty logic
- [x] add difficulty filter
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
