### ISSUE TITLE
card-decks-page

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#24]
## Value Proposition

**As a** User
**I need** to create decks of cards
**to be able to** decide precisely how much I want to study and to increase motivation

## Description
<img src="https://user-images.githubusercontent.com/98178752/162566821-6dc659be-50f9-4f96-afc4-869226ddaf2f.png" alt="wireframe: card decks page" width="300"/>

Branch: `card-decks-page`

## Acceptance Criteria

- [x] new page: 'Deck erstellen'
- [x] decksize: 5
- [x] filter with adjustable category and difficulty
- [x] click on button 'nächste Karte' shows next card of deck
- [x] click on 'Beenden' button quits deck and gets back to 'Deck erstellen'
- [x] at the end of deck: 'Möchtest du von vorne anfangen?' message
- [x] yes shows first card of current deck, no shows 'Deck erstellen'
- [x] <del>decks are not saved in localStorage()</del>   QA showed, that it's better for the user to save decks in localStorage

## Tasks

- [x] add page CreateDeck
- [x] add CreateDeck.spec
- [x] add form with with Filter.js
- [x] add logic to display only one card
- [x] add 'nächste Karte' button
- [x] add logic to display next card
- [x] add 'Beenden' button
- [x] add quit logic
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
