### ISSUE TITLE
expand-decks-page

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#29]
## Value Proposition

**As a** User
**I need** have different options to create my deck
**to be able to** study in different situations, convenient to my needs

## Description
<img src="https://user-images.githubusercontent.com/98178752/162566821-6dc659be-50f9-4f96-afc4-869226ddaf2f.png" alt="wireframe: card decks page" width="300"/>

Branch: `expand-decks-page`

## Acceptance Criteria

- [x] adjustable size of deck, required

## Tasks

- [x] update CreateDeck.spec
- [x] update size
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
