### ISSUE TITLE
toggle-answer

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#3]
## Value Proposition

**As a** User
**I need** to hide the answer
**to be able to** study better

## Acceptance Criteria

- [ ] answer toggles when button is clicked

## Tasks

- [ ] create branch `toggle-answer`
- [ ] create button 'Show Answer' and toggle logic
- [ ] update Card with storybook and specs
- [ ] update styles
- [ ] test on different devices/browsers

**Comment by PReichetanz** [comment]
Regarding the UX: I think it would be better if the toggle button stays at the same place instead of going down under the answer; by doing so, the user can toggle more quickly (and thus learn better). What do you think?

**Comment by Ju-Schn** [comment]
> Regarding the UX: I think it would be better if the toggle button stays at the same place instead of going down under the answer; by doing so, the user can toggle more quickly (and thus learn better). What do you think?

Hi Paul, thanks for your comment. Does the 'Arrow up'-icon make sense if it's displayed between the question and the answer? Because the answer will be hidden onClick, not the question.. Or should I use another icon then? What do you think?
