### ISSUE TITLE
add-backend

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#32]
## Value Proposition

**As a** User
**I need** to share cards with others in a study group 
**to be able to** split work

## Description
Cards are available on different devices.
Different students on different devices can create cards that are available for everyone.

Branch: `add-backend`

## Acceptance Criteria

- [x] it's possible to create and delete cards from different devices
- [x] bookmark & counter are saved only locally

## Tasks

- [x] setup mongoDB
- [x] add .env
- [x] add index.http
- [x] update add functionality
- [x] update delete functionality
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
