### ISSUE TITLE
add-login

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#33]
## Value Proposition

**As a** User
**I need** to share my cards only within my study group
**to be able to** keep it simple and clearly organized

## Description

Branch: `add-login`

## Acceptance Criteria

- [ ] login in with username and password
- [ ] error message when username or password is wrong
- [ ] empty inputs do not submit

## Tasks

- [ ] add login page with inputs
- [ ] add login.spec
- [ ] add error message
- [ ] add login data
- [ ] update App
- [ ] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
