### ISSUE TITLE
success-message

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#34]
## Value Proposition

**As a** User
**I need** know if my card was created successfully
**to be able to** add more than one card without interruption because of checking

## Description
<img src="https://user-images.githubusercontent.com/98178752/163827693-1ffa2e5f-ac3d-45ca-811a-085c0dcf609a.png" alt="wireframe: success message" width="300"/>

Branch: `success-message`

## Acceptance Criteria

- [ ] success message shows if card is added successfully
- [ ] duration: 2 seconds

## Tasks

- [ ] add success message
- [ ] update CreateCard page
- [ ] update CreateCard.spec
- [ ] update submit function
- [ ] update styling
- [ ] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
