### ISSUE TITLE
counter-message

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#35]
## Value Proposition

**As a** User
**I need** to know if I clicked my count
**to be able to** count my right and wrong answers precisely and not click 2 times accidentally

## Description
<img src="https://user-images.githubusercontent.com/98178752/163949533-6036200b-d4fc-4c4c-93b7-11de225bb691.png" alt="wireframe: counter message" width="300"/>

Branch: `counter-message`

## Acceptance Criteria

- [x] count message shows if count is clicked
- [x] duration: 2 seconds

## Tasks

- [x] add count message
- [x] update Card component
- [x] update Card.spec
- [x] update count functions
- [x] update styling
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
