### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#37]
## Value Proposition

**As a** User
**I need** a clearly represented app instruction
**to be able to** quickly catch up on the app's functions

## Description
A well-arranged, appealing readme file provides information about the 
app's functions for users

Branch: `readme`

## Acceptance Criteria

- [x] readme is clearly arranged
- [x] pictures are added for better understanding
- [x] readme is provided in german and english language

## Tasks

- [x] update README.md
- [x] add pictures of important buttons and functionalities
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
