### ISSUE TITLE
add-local-storage

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#4]
## Value Proposition

**As a** User
**I need** my created cards to be saved 
**to be able to** still use them after closing the app

## Description

Add local storage to save the cards' information when the app is reloaded or reopened after closing

## Acceptance Criteria

- [x] cards persist when the app is reopened or reloaded

## Tasks

- [x] create branch `add-local-storage`
- [x] update App.spec
- [x] update App: add localStorage() 
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
