### ISSUE TITLE
landing-page

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#40]
## Value Proposition

**As a** User
**I need** a summary of the app's functions when I start the it
**to be able to** navigate quickly to the right page for my needs

## Description

<img src="https://user-images.githubusercontent.com/98178752/164646562-880b1446-87f6-4014-be41-4783022cabaf.png" alt="wireframe: landing page" width="300"/>

Branch: `landing-page`

## Acceptance Criteria

- [x] landing page on route '/'
- [x] page without navigation footer
- [x] short descriptions of all pages
- [x] <del>button with link for each page</del>   styled navigation links

## Tasks

- [x] add landing page
- [x] add landing.spec
- [x] update navigation specs
- [x] <del> add buttons with useNavigate()</del> add NavLinks 
- [x] add NavLink styling
- [x] update Routes in App component
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
