### ISSUE TITLE
add-loading-spinner

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#45]
## Value Proposition

**As a** User
**I need** a pleasant loading animation
**to be able to** hold my motivation while the app is loading

## Description

animated loading spinner is shown whenever app or database is loading

Branch: `add-loading-spinner`

## Acceptance Criteria

- [ ] loading spinner appears, whenever app is loading

## Tasks

- [ ] add loading spinner
- [ ] add loading.spec
- [ ] update App
- [ ] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
