### ISSUE TITLE
toggle-bookmark

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#5]
## Value Proposition

**As a** User
**I need** to bookmark cards
**to be able to** find them easier and recap them

## Description
<img src="https://user-images.githubusercontent.com/98178752/159939485-e9820910-13c8-4f32-abc6-e1604c247190.png" alt="wireframe: cards with toggle bookmark button and different background-color" width="300"/>

Branch: `toggle-bookmark`

## Acceptance Criteria

- [x] bookmark toggles when button is clicked
- [x] card gets a different background-color if it is bookmarked
- [x] bookmark button is accessible

## Tasks

- [x] update Card.spec
- [x] update Card.stories 
- [x] create button with icon 
- [x] implement toggle logic
- [x] update styling
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
