### ISSUE TITLE
delete-card

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#6]
## Value Proposition

**As a** User
**I need** to delete cards that I don't need anymore
**to be able to** clear my card list for better survey

## Description
<img src="https://user-images.githubusercontent.com/98178752/159940710-4b187070-683c-4eaa-aeae-091af122e158.png" alt="wireframe: cards with toggle bookmark button and navigation" width="300"/>

Branch: `delete-card`
## Acceptance Criteria

- [x] when delete button is clicked: show alert 'Möchtest du die Karte wirklich löschen?'
- [x] card is deleted when alert is submitted 

## Tasks

- [x] update Card.spec
- [x] update Card.stories 
- [x] create delete button with icon 
- [x] create alert message
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
