### ISSUE TITLE
bookmark-page

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#7]
## Value Proposition

**As a** User
**I need** a page for bookmarked cards
**to be able to** recap only bookmarked cards

## Description
<img src="https://user-images.githubusercontent.com/98178752/159943001-8e250c2e-8fd8-4db4-ae58-ae88a5d27fcf.png" alt="wireframe: cards with toggle bookmark button and navigation" width="300"/>

Branch: `bookmark-page`

## Acceptance Criteria

- [x] cards <del>switch</del> are copied to bookmark page when bookmark button is clicked
- [x] <del>card switches back to home, when it is un-bookmarked</del> **Decided to show pinned cards on both pages for better user experience after user review**
- [x] bookmark button is only visible when answer is visible
- [x] navigation leads to different pages

## Tasks

- [x] add bookmarked page
- [x] add navigation on all pages
- [x] add react Router
- [x] update toggle logic
- [x] update styling
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
