### ISSUE TITLE
question-categories

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#8]
## Value Proposition

**As a** User
**I need** to categorize cards (e.g. 'History' or 'HTML')
**to be able to** quickly decide if I want to answer them

## Description
<img src="https://user-images.githubusercontent.com/98178752/159950648-03627ddf-535f-4473-b2a4-1ea1066fae3d.png" alt="wireframe: updated form and cards with categories" width="300"/>

Branch: `question-categories`

## Acceptance Criteria

- [x] new 'Kategorie' input in form
- [x] categories are displayed below question

## Tasks

- [x] update CardForm.spec
- [x] update CardForm
- [x] update Card.spec
- [x] update Card.stories
- [x] update Card
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
