### ISSUE TITLE
category-search

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/capstone-project#9]
## Value Proposition

**As a** User
**I need** to filter cards by category
**to be able to** recap exactly what I need to memorize for the next test

## Description
<img src="https://user-images.githubusercontent.com/98178752/159958966-c5b0c7e0-bef0-4f82-b294-d82e030b07a1.png" alt="wireframe: searchbar and cards with category" width="300"/>

Branch: `category-search`

## Acceptance Criteria

- [x] when input is empty or only whitespace search doesn't submit
- [x] search is not case sensitive    
- [x] after submit: list shows only cards with matching category
- [x] when there are no matches in categories show: 'Es gibt noch keine Karten in dieser Kategorie.'  

## Tasks

- [x] update CardList.spec
- [x] update CardList
- [x] add filter logic
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
